version: '3.8'

services:
  RequirementsProject:
    image: postgres:latest
    container_name: RequirementsProject
    environment:
      POSTGRES_DB: EcommerceDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_*01
    ports:
      - "5000:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata: